### ISSUE TITLE
Cypress incompatibility

### ISSUE THREAD

**Issue by aurishAtKnysys** [accredible/accredible_certificate#1]
The following problems are faced while issuing accredible_certificate from edx (Cypress)

*Course id's have been changed from 
edX/DemoX/Demo_Course
to
course-v1:edX+DemoX+Demo_Course

*After changing the ids

Traceback (most recent call last):
  File "./manage.py", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/accredible_certificate/management/commands/generate_accredible_certs.py", line 112, in handle
    ret = xq.add_cert(student, course_key, new_status, course=course)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/accredible_certificate/queue.py", line 145, in add_cert
    user_is_reverified = SoftwareSecurePhotoVerification.user_is_reverified_for_all(course_id, student)
AttributeError: type object 'SoftwareSecurePhotoVerification' has no attribute 'user_is_reverified_for_all'

I think user_is_reverified_for_all is removed from Cypress so changed the logic related to user_is_reverified_for_all

*Now getting the following info and nothing is happening after it.

2015-12-12 02:20:30,013 INFO 4749 [edx.courseware] grades.py:143 - Signal fired when student grade is calculated. Receiver: <function listen_for_grade_calculation at 0x815c410>. Response: None

**Comment by alanheppenstall** [comment]
Resolved with the pull request from @mbifulco
